# Generated by Django 5.0.9 on 2024-11-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandUsers',
        ),
    ]
