# Generated by Django 5.0.9 on 2024-10-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("AMAZON", "AMAZON")], default="AMAZON", max_length=10
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("US", "US"),
                            ("IN", "IN"),
                            ("CA", "CA"),
                            ("MX", "MX"),
                            ("BR", "BR"),
                            ("AU", "AU"),
                            ("JP", "JP"),
                            ("SG", "SG"),
                            ("AE", "AE"),
                            ("SA", "SA"),
                            ("TR", "TR"),
                            ("EG", "EG"),
                            ("PL", "PL"),
                            ("SE", "SE"),
                            ("IT", "IT"),
                            ("NL", "NL"),
                            ("ES", "ES"),
                            ("UK", "UK"),
                            ("FR", "FR"),
                            ("DE", "DE"),
                        ],
                        default="US",
                        max_length=5,
                    ),
                ),
                ("config", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Marketplace",
                "verbose_name_plural": "Marketplaces",
                "db_table": '"amazon"."marketplace"',
            },
        ),
    ]
