# Generated by Django 5.0.9 on 2024-10-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0005_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotions",
            name="discount_percentage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
