# Generated by Django 5.0.9 on 2024-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0006_alter_promotions_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotions",
            name="discount_percentage",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="promotions",
            name="price",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
