# Generated by Django 5.0.9 on 2024-10-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0007_alter_promotions_discount_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bsr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("asin", models.CharField(blank=True, max_length=255, null=True)),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "amazon_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("offers_count", models.IntegerField(blank=True, null=True)),
                (
                    "rank_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("thumbnail_image", models.URLField(blank=True, null=True)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="amazon.marketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Best Seller Rank",
                "verbose_name_plural": "Best Seller Ranks",
                "db_table": '"amazon"."bsr"',
            },
        ),
    ]
