# Generated by Django 5.0.9 on 2024-10-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0008_bsr"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("asin", models.CharField(blank=True, max_length=255, null=True)),
                ("sold_by", models.CharField(blank=True, max_length=255, null=True)),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
                ("ships_from", models.CharField(blank=True, max_length=255, null=True)),
                ("shipping_price", models.FloatField(blank=True, null=True)),
                (
                    "shipping_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="amazon.marketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Profile",
                "verbose_name_plural": "Seller Profiles",
                "db_table": '"amazon"."sp"',
            },
        ),
    ]
