# Generated by Django 5.0.9 on 2024-10-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0009_sellerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("asin", models.CharField(blank=True, max_length=255, null=True)),
                ("features", models.TextField(blank=True, null=True)),
                (
                    "media_alt_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("deal_type", models.FloatField(blank=True, null=True)),
                ("deal_state", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "deal_access_behaviour",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "deal_early_access_duration_in_ms",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("deal_percentage_claimed", models.FloatField(blank=True, null=True)),
                ("deal_start_time", models.DateTimeField(blank=True, null=True)),
                ("deal_end_time", models.DateTimeField(blank=True, null=True)),
                ("deal_id", models.CharField(blank=True, max_length=255, null=True)),
                ("mrp", models.FloatField(blank=True, null=True)),
                ("selling_price", models.FloatField(blank=True, null=True)),
                (
                    "discount_percentage",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "parent_five_star_rating_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "parent_four_star_rating_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "parent_three_star_rating_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "parent_two_star_rating_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "parent_one_star_rating_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("max_order_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "is_max_order_quantity_set",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "availability",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "availability_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="amazon.marketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": '"amazon"."product"',
            },
        ),
    ]
