# Generated by Django 5.0.9 on 2024-11-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
